---
title: "Dissolved Oxygen Markdown"
output: html_document
date: "2024-02-14"
---
```{r}
require("tidyverse")
require("lubridate")
require ("ggplot2")
```

```{r}
#Read in csv file 
Totalr1DO <- read.csv("../data/HoboData/Totalr1DO.csv")

#Format date
Totalr1DO$Date2 <- as.Date(Totalr1DO$Date,"%m/%d/%Y")

#remove negative  values 
Totalr1DO$DO_concentration[Totalr1DO$DO_concentration<0] <- 0 

#Plot and format graoh 
plot.R1DO <- ggplot(
  data = Totalr1DO, aes(x = Date2, y = DO_concentration, group=1)
 ) +
  geom_line(data = Totalr1DO[1:21698, ], aes(x = Date2, y=DO_concentration, group = 1 )) +
  geom_line(data = Totalr1DO[21699:length(Totalr1DO$Date), ], aes(x = Date2, y=DO_concentration, group = 2)) +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Dissolved Oxygen (mg/L)")+
     scale_x_date(date_labels = "%b %y", date_breaks = "2 month")+
#expand limits
        expand_limits(x = as.Date(c("2022-01-01", "2022-11-01")))+ 
          expand_limits(y = c(0,15)) + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.R1DO
```
```{r}
#read in csv file 
TotalR3DO <- read.csv("../data/HoboData/TotalRiffle3do.csv")

#format date 
TotalR3DO$Date2 <- as.Date(TotalR3DO$Date,"%m/%d/%Y")
TotalR3DO$DO_concentration[TotalR3DO$DO_concentration<0] <- 0

#Plot and format graoh 
plot.R3DO <- ggplot(
data = TotalR3DO, aes(x = Date2, y = DO_concentration, group=1)
) +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Dissolved Oxygen (mg/L)",)+
     scale_x_date(date_labels = "%b %y", date_breaks = "1 month")+
     theme(axis.text.x = element_text(angle=45, hjust = 1))+
  #expand limits
        expand_limits(x = as.Date(c("2022-01-01", "2022-11-01")))+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.R3DO

```

