---
title: "Graphing Markdwon"
output: html_document
date: "2023-10-18"
---

```{r setup, include=FALSE}
rm(list = ls())
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set("~/github/TownCreekWater/analyses")
```

```{r packgages}
require("tidyverse")
require("lubridate")
require("ggpubr")
require('scales')
```


```{r working date plot - Riffle 1 Water Level}
#FinalRiffle1 <- read.csv("C:\\Users\\Teten\\Documents\\HOBOware\\Final_Total_Riffle1.csv") # Tete's Windows path

# Relative path:
FinalRiffle1 <- read.csv("../data/HoboData/Final_Total_Riffle1.csv")

# Format date:
FinalRiffle1$Date2 = as.Date(FinalRiffle1$Date,"%m/%d/%Y")

#plot graph, expand limits (x & y axis), format plot 
plot.R1WL <- ggplot(
  data = FinalRiffle1, aes(x = Date2, y = Sensor_Depth, group=1)
 ) +
     geom_line() +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Sensor Depth (m)",)+
  #expand limits:
              expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
              expand_limits(y = c(0, 2.5)) + 
     scale_x_date(date_labels = "%b %y", date_breaks = "3 month")+
   theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.R1WL

# I removed "Date" from X-axis because the tick labels make it clear enough that it's a date
```

```{r working date plot - Riffle 3 Water Level}
# Read in data:
FinalRiffle3 <- read.csv("../data/HoboData/Totalriffle3.csv")


# Format date:
FinalRiffle3$Date2 = as.Date(FinalRiffle3$Date,"%m/%d/%Y")

#range <-  c(as.Date(x = "Feb 22",format= "%b %y"), as.Date("Nov 23", "%b %Y"))

#plot graph, expand limits (x & y axis), format plot: 
plot.R3WL <- ggplot(data = FinalRiffle3, aes (x = Date2, y = Sensor_Depth, group=1)) + 
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Sensor Depth (m)",) +

     #expand limits:
         expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
         expand_limits(y = c(0, 2.5)) + 

   scale_x_date(date_labels = "%b %y", date_breaks = "3 months")+
      theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))

plot.R3WL  


```

```{r working date plot - Piezometer Shallow}
# Read in data:
TotalPiezometerShallow <- read.csv("../data/HoboData/TotalRSC_Piezometer_shallow.csv")

# Format date:
TotalPiezometerShallow$Date2 = as.Date(TotalPiezometerShallow$Date,"%m/%d/%Y")

#Plot graph, expand limits (x & y axis), format plot: 
plot.TPS <- ggplot(
  data = TotalPiezometerShallow, aes(x = Date2, y = Sensor_Depth, group=1)
 ) +
     geom_line() +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Sensor Depth (m)",)+
  #expand limits 
    expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
    expand_limits(y = c(0, 2.5)) + 

   scale_x_date(date_labels = "%b %y", date_breaks = "3 months")+
    theme_bw() +
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))

plot.TPS
```

```{r - working date plot - Small RSC Down}
# Read in data:
TotalSmallRSCDown <- read.csv("../data/HoboData/Total_Small_RSC_Down.csv")

# Format date:
TotalSmallRSCDown$Date2 = as.Date(TotalSmallRSCDown$Date,"%m/%d/%Y")

#Remove negative sensor depth 
TotalSmallRSCDown$Sensor_Depth[TotalSmallRSCDown$Sensor_Depth<0] <- 0 


#plot graph, expand limits (x & y axis), format plot: 
plot.TSRSCD <- ggplot(
  data = TotalSmallRSCDown, aes(x = Date2, y = Sensor_Depth, group=1)
 ) +
     geom_line() +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "",)+
    #expand limits (not on y-axis since this was used as the largest range:
    expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
   scale_x_date(date_labels = "%b %y", date_breaks = "3 months")+
 theme_bw() +
expand_limits(y = c(0, 2.5)) + 
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.TSRSCD
```

```{r working date plot - Piezometer Deep Water Level}
# Read in data:
TotalPiezometerDeep <- read.csv("../data/HoboData/Totalrsc_piezometer_deep.csv")

# Format date:
TotalPiezometerDeep$Date2 = as.Date(TotalPiezometerDeep$Date,"%m/%d/%Y")

#plot graph, expand limits (x & y axis), format plot: 
plot.TPD <- ggplot(
  data = TotalPiezometerDeep, aes(x = Date2, y = Sensor_Depth, group=1)
 ) +
     geom_line() +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Sensor Depth (m)",)+
theme_bw() +
    #expand limits:
    expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
   scale_x_date(date_labels = "%b %y", date_breaks = "3 months")+
  #Remove plot grid lines
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.TPD
```


```{r - working date plot - Small RSC Up}
# Read in data:
TotalSmallRSCUp <- read.csv("../data/HoboData/TotalTC_Small_RSC_Up.csv")

# Format date:
TotalSmallRSCUp$Date2 <- as.Date(TotalSmallRSCUp$Date,"%m/%d/%Y")

#Remove negative sensor depths
TotalSmallRSCUp$Sensor_Depth[TotalSmallRSCUp$Sensor_Depth<0] <- 0 


# plot graph, expand limits (x & y axis), format plot: 
plot.TSRSCU <- ggplot(
  data = TotalSmallRSCUp[1:39859,], aes(x = Date2, y = Sensor_Depth, group=1)
 ) +
     geom_line() +
     geom_point(size=.25)+ 
     labs(
         title = "",
         x = "", y = "Sensor Depth (m)",) +
    #expand limits:
    expand_limits(x = as.Date(c("2022-01-01", "2023-12-15")))+ 
   scale_x_date(date_labels = "%b %y", date_breaks = "3 months")+
      theme_bw() +
    expand_limits(y = c(0, 2.5)) + 
  #Remove plot grid lines
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  #Set axis title and text properties, tick marks, and labels
  theme(text=element_text(size=20),axis.title=element_text(size=20,face="bold"),
          axis.text=element_text(size=15),  
          axis.title.y=element_text(margin=margin(r=10)),
          axis.title.x = element_text(margin = margin(r=10)),
          panel.border = element_rect(colour = "black",linewidth=1),strip.text = element_text(size = 20), legend.position="none", legend.title = element_text(size=20), legend.text=element_text(size=20)) + 
          theme(axis.ticks.length=unit(0.3,"cm")) + 
  theme(rect=element_rect(fill="transparent"))+
  theme(plot.background = element_rect(color=NA), axis.text.x = element_text(angle=45, hjust = 1))


plot.TSRSCU
```

```{r four panel water level}
four_panel_IS_Dry_up_Down <- ggarrange(plot.R1WL, plot.TSRSCU, plot.R3WL, plot.TSRSCD, ncol = 2, nrow = 2, labels = c("A", "B", "C", "D"), legend = "none")

four_panel_IS_Dry_up_Down

#ggsave("../figures/WaterLVL.png", plot=four_panel_IS_Dry_up_Down, device="png", path=NULL, scale=1, width=14, height=10, dpi=600, limitsize=TRUE, bg="white")
```

